import type { Session } from '@domain/types/auth.types';

/**
 * Report export (P16 §12). CSV today; the same envelope serves future Excel/PDF and
 * scheduled exports. Every export preserves report integrity: title, timestamp, the
 * applied filters, column definitions and who generated it.
 */
export interface ExportColumn<T> {
  header: string;
  value: (row: T) => string | number | null;
}

/**
 * Leading characters a spreadsheet treats as the start of a FORMULA rather than text.
 *
 * Ticket subjects, category labels and requester names are free user text and were written to the
 * file unmodified. A subject beginning `=`, `+`, `-`, `@`, a tab or a carriage return is executed
 * by Excel, Numbers and Sheets when the export is opened — so a value one person typed into a
 * ticket could run in the spreadsheet of whoever downloaded the report. Quoting does not prevent
 * it; the leading character has to be neutralised.
 */
const RISKY_LEAD = /^[=+\-@\t\r]/;

const esc = (v: unknown): string => {
  let s = v === null || v === undefined ? '' : String(v);
  // A leading apostrophe is the standard defence: the cell is treated as text and the apostrophe
  // is not displayed, so what a human reads is unchanged.
  if (RISKY_LEAD.test(s)) s = `'${s}`;
  // A lone carriage return breaks a row in some readers, so it needs quoting as much as \n does.
  return /[",\n\r]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
};

export const ExportService = {
  /** Build a CSV string with the P16 §12 metadata header block. */
  buildCsv<T>(
    title: string,
    rows: readonly T[],
    columns: readonly ExportColumn<T>[],
    filters: string,
    session: Session,
    /** The scope clamp the rows were drawn from. Optional only so existing callers still compile. */
    scope?: string,
  ): string {
    const meta = [
      `# Report,${esc(title)}`,
      `# Generated,${esc(new Date().toISOString())}`,
      `# Generated by,${esc(`${session.user.name} (${session.user.departmentCode})`)}`,
      // The scope clamp, which the header never recorded. Two exports of "everything, no filters"
      // — one by Sales, one by a sysadmin — produced identical-looking headers over completely
      // different populations. A file outlives the screen it came from and has to carry its own
      // context.
      `# Data scope,${esc(scope ?? 'Unrecorded')}`,
      `# Filters,${esc(filters)}`,
      `# Rows,${rows.length}`,
      '',
    ].join('\n');
    const head = columns.map((c) => esc(c.header)).join(',');
    const body = rows.map((r) => columns.map((c) => esc(c.value(r))).join(',')).join('\n');
    return `${meta}${head}\n${body}\n`;
  },

  /** Trigger a client-side download (no backend). */
  download(filename: string, csv: string): void {
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  },
};
